// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfI5p2sYcjTjjdWDHNaqKX9t9JNXNgZD4',
    appId: '1:408276834554:web:56169df319f929210f1143',
    messagingSenderId: '408276834554',
    projectId: 'boi-pori-5',
    authDomain: 'boi-pori-5.firebaseapp.com',
    storageBucket: 'boi-pori-5.appspot.com',
    measurementId: 'G-JLR8CDR597',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvkxdDcMwxq9u-IVWesVTAZGNbO8GJjU',
    appId: '1:408276834554:android:777c4f29e898a6e10f1143',
    messagingSenderId: '408276834554',
    projectId: 'boi-pori-5',
    storageBucket: 'boi-pori-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDww-DjgLFKBuvd8mZYVndtD6qZ1DI9dZg',
    appId: '1:408276834554:ios:84a0b1244b6198250f1143',
    messagingSenderId: '408276834554',
    projectId: 'boi-pori-5',
    storageBucket: 'boi-pori-5.appspot.com',
    iosBundleId: 'com.mhs.co.ltd.boiporo',
  );
}
